name: Benchmark weldx import timing
on:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: Run pytest-benchmark on weldx import timing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
      - name: install python packages
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          pip install wheel
          pip install -r requirements.txt
 
      - name: Run benchmark
        run: |
         pytest bench.py --benchmark-json output.json || true
      - name: Store benchmark result
        if: 0 == 1
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: output.json
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '110%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@marscher'
